### PR TITLE
Update labeler to use the head ref when accessing the config so that the labeler can see updates to the config within the PR

### PR DESCRIPTION
**Pull request by TheCleric**

### CODE REVIEW

**Comment by TheCleric** [comment]
This will fix https://github.com/ffittschen/pr-branch-labeler/issues/7

**Comment by ffittschen** [comment]
Thanks for taking the time to fix this! Did you create the branch based of the `release/v1` branch? There are some old commits from me that show up in this history. Could you please rebase this PR onto `master`?

**Comment by TheCleric** [comment]
Yes this was off v1. I'll try to rebase it.

**Comment by TheCleric** [comment]
This should be better now.

**Comment by TheCleric** [comment]
Closing this PR as I've merged more code into my master that has polluted it. Will create an unpolluted PR.

**Pull request closed without merging**
